### PR TITLE
Revert "First Draft"

### PR DESCRIPTION
**Pull request by SupTrip**
Reverts padhuashok/invoicify#9

### CODE REVIEW

**Review by padhuashok — CHANGES_REQUESTED** [review]
please add additional info

**Comment by padhuashok** [comment]
please add more info

**Review by padhuashok — CHANGES_REQUESTED** [review]
test review to request changes

**Review by padhuashok — DISMISSED** [review]
Hi Supriya, is this request still valid?

**Comment by SupTrip** [comment]
This has been addressed separately

**Pull request closed without merging**
